name: time-tracking

services:
  mongodb:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - time-tracking-mongodb-data:/data/db

volumes:
  time-tracking-mongodb-data:
